"""Tests for init default engine provider — must map to a registered factory.

Regression test for MVP blocker: ``miniautogen init`` was generating config
with ``provider: litellm`` but no litellm driver factory was registered,
causing users to crash on first run.
"""

from __future__ import annotations

import inspect

import yaml

from miniautogen.backends.config import DriverType
from miniautogen.backends.engine_resolver import (
    EngineResolver,
    _PROVIDER_TO_DRIVER,
)
from miniautogen.cli.services.init_project import scaffold_project


def test_init_default_engine_has_working_provider(tmp_path) -> None:
    """The default engine from init should use a provider with a registered factory."""
    # Get the default provider from scaffold_project signature
    sig = inspect.signature(scaffold_project)
    default_provider = sig.parameters["provider"].default

    # Verify the provider has a DriverType mapping
    assert default_provider in _PROVIDER_TO_DRIVER, (
        f"Default provider '{default_provider}' has no DriverType mapping"
    )

    # Verify the DriverType has a registered factory
    driver_type = _PROVIDER_TO_DRIVER[default_provider]
    resolver = EngineResolver()
    registered = resolver._resolver._factories  # noqa: SLF001
    assert driver_type in registered, (
        f"Default provider '{default_provider}' maps to DriverType.{driver_type.name} "
        f"but no factory is registered for it. "
        f"Registered factories: {list(registered.keys())}"
    )


def test_init_generated_config_has_valid_provider(tmp_path) -> None:
    """The YAML config generated by init must reference a provider with a factory."""
    project_dir = scaffold_project("test-project", tmp_path)
    config_path = project_dir / "miniautogen.yaml"
    config = yaml.safe_load(config_path.read_text())

    engines = config.get("engines", {})
    assert engines, "Generated config should have at least one engine"

    resolver = EngineResolver()
    registered = resolver._resolver._factories  # noqa: SLF001

    for engine_name, engine_cfg in engines.items():
        provider = engine_cfg["provider"]
        assert provider in _PROVIDER_TO_DRIVER, (
            f"Engine '{engine_name}' uses provider '{provider}' "
            f"which has no DriverType mapping"
        )
        driver_type = _PROVIDER_TO_DRIVER[provider]
        assert driver_type in registered, (
            f"Engine '{engine_name}' uses provider '{provider}' "
            f"(DriverType.{driver_type.name}) but no factory is registered"
        )
