"""Protocol defining the data provider interface for Console Server routes."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ConsoleDataProvider(Protocol):
    """Protocol for data providers used by Console Server routes.

    DashDataProvider is the primary implementation.
    """

    def get_config(self) -> dict[str, Any]: ...
    def get_agents(self) -> list[dict[str, Any]]: ...
    def get_agent(self, name: str) -> dict[str, Any]: ...
    def get_pipelines(self) -> list[dict[str, Any]]: ...
    def get_pipeline(self, name: str) -> dict[str, Any]: ...
    def get_runs(self) -> list[dict[str, Any]]: ...
    def get_events(self) -> list[dict[str, Any]]: ...
    def record_run(self, run_data: dict[str, Any]) -> None: ...
    def update_run(self, run_id: str, updates: dict[str, Any]) -> None: ...
    async def run_pipeline(
        self,
        pipeline_name: str,
        *,
        event_sink: Any | None = None,
        timeout: float | None = None,
        pipeline_input: str | None = None,
        run_id: str | None = None,
    ) -> dict[str, Any]: ...
